### ISSUE TITLE
about memo

### ISSUE THREAD

**Issue by zychappy** [denkhaus/bitshares#10]
why "from " of memo is a  struct not a string? If I have had memo_keys, how could I change to public_key struct?

**Comment by denkhaus** [comment]
Hi @zychappy , from and to is PublicKey type defined in types. You can create a new public key by calling e.g. NewPublicKeyFromString("BTS6K35Bajw29N4fjP4XADHtJ7bEj2xHJ8CoY2P2s1igXTB5oMBhR").
Then you init the Memos "From" and "To" Fields, call func (p *Memo) Encrypt(priv *PrivateKey, msg string) to encrypt your message and you're good to go.
