### ISSUE TITLE
NewLimitOrderCreateOperation failing missing required active authority

### ISSUE THREAD

**Issue by wshaman** [denkhaus/bitshares#13]
Trying to call `limit_order_create` fails for me with `missing required active authority: Missing Active Authority 1.2.*`
Steps to reproduce:
```go
	btsLib := _create_a_api.BitsharesAPI_
	wif := "5......."
	sender := types.NewGrapheneID("1.2...")
	bts := types.NewGrapheneID("1.3.0")
	cny := types.NewGrapheneID("1.3.113")
	keys :=  crypto.NewKeyBag()
	err := keys.Add(wif)
	expir := time.Now().AddDate(1,0,0)
	op := operations.NewLimitOrderCreateOperation()
	op.AmountToSell = types.AssetAmount{
		Amount:100,
		Asset: *bts,
	}
	op.MinToReceive = types.AssetAmount{
		Amount:10000,
		Asset:*cny,
	}
	op.Seller = *sender
	op.FillOrKill = false
	op.Expiration = types.Time{Time:expir}
	tx, err := btsLib.BuildSignedTransaction(keys, bts, op)
	if err != nil {
		return err
	}
	return btsLib.BroadcastTransaction(tx)
```
Note: 
```go
	op := operations.NewTransferOperation()
	op.Amount = types.AssetAmount{
		Amount:100,
		Asset: *bts,
	}
	op.From = *sender
	op.To = *rcvr
```
This operation works well, transaction created, signed and broadcast without any error using same account and wif.

**Comment by denkhaus** [comment]
Thank you. I will shortly look into it.

**Comment by denkhaus** [comment]
Hi @wshaman so far i cannot reproduce your issue. I created a snippet in examples/limitorder for you, which is running without errors in my environment. Please contact me if this does not work for you.

**Comment by wshaman** [comment]
Thank you, @denkhaus 
It was my error - `op.Expiration = types.Time{Time:expir}` is wrong assignment, I should use `op.Expiration.Set()` call to create an order properly.
