### ISSUE TITLE
Memo working snippet

### ISSUE THREAD

**Issue by saniales** [denkhaus/bitshares#15]
Hello,
I am having a lot of errors in creating memos

Can you kindly provide a working snippet to send a memo in a transaction from A to B?
I assume you have PrivA and PubB and you want to send an encrypted memo

**Comment by denkhaus** [comment]
Hi @saniales , after reviewing the code i see your issue. I think it's more straightforward to call memo.Decrypt from the receiver perspective. So the shared secret is built from the receivers priv key and the senders pub key (From). I changed the code and docs accordingly. You will find a working snippet under examples/memo.
