### ISSUE TITLE
after tranfer succussfully could not decrypt memo

### ISSUE THREAD

**Issue by zychappy** [denkhaus/bitshares#23]
your transfer example is running smoothing,
1.2.17 transfer 1.20000 BTS to 1.2.29,memo is :"my super secret memo message",
the 1.2.29 history like below,
```
 "memo": {
                            "from": "BTS6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV",
                            "message": "35613537366637313638363336663634366233383638343634623461326233363733373433353631353937303535333436383466333934613735363736363533353936653539353836313533363834313735326633343364",
                            "nonce": "5577006791947779410",
                            "to": "BTS8iYeD3bwfnCZk3BCXeAzJXGL5r2mVz8k3qTMUJrhT7xXf1zuc5"
```
when I check in wallet cli,I found the message can't decrypt
```
2019-03-12T06:51:40 Transfer 1.20000 BTS from nathan to nathan2 -- could not decrypt memo
```
maybe something happened I don't know?

**Comment by denkhaus** [comment]
Sorry @zychappy this is a known issue. Memos sent by this library are not compatible with memos created by bitsharesjs. If I recall correctly, xeroc's python lib isn't either.

**Comment by zychappy** [comment]
I checked the source code,the else part serialize message directly without the keys,maybe this is an optional solution？just serialize the message?
```
void memo_data::set_message(const fc::ecc::private_key& priv, const fc::ecc::public_key& pub,
                         const string& msg, uint64_t custom_nonce)
{
if( priv != fc::ecc::private_key() && public_key_type(pub) != public_key_type() )
{
  ...
}
else
{
   auto text = memo_message(0, msg).serialize();
   message = vector<char>(text.begin(), text.end());
}
}```

**Comment by denkhaus** [comment]
Hi @zychappy look at branch memo_experiment ea2b5180378ba6146833000292f8df0f89a2633e . This was one attempt to make memo handling compatible with bitsharesjs. Maybe that's a good base to look into it. Unfortunately I have little time at the moment to continue here.

**Comment by zychappy** [comment]
@denkhaus 
Thank you for your reply.
Still I can solve this problem,
but I found another way :sign_memo and read_memo of the wallet-api 
```
sign_memo 1.2.17 1.2.29 "my super secret memo message"
{
  "from": "BTS6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV",
  "to": "BTS8iYeD3bwfnCZk3BCXeAzJXGL5r2mVz8k3qTMUJrhT7xXf1zuc5",
  "nonce": "3892662880978795017",
  "message": "16ba135146afed0633249810070d1e65660cde3d3f2aef258416633cdf665d74798b7ecb3be98cee05593432dee4b932"
}

read_memo {"from":"BTS6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV","to":"BTS8iYeD3bwfnCZk3BCXeAzJXGL5r2mVz8k3qTMUJrhT7xXf1zuc5","nonce":"3892662880978795017","message":"16ba135146afed0633249810070d1e65660cde3d3f2aef258416633cdf665d74798b7ecb3be98cee05593432dee4b932"}
"my super secret memo message"
```

maybe it is also helpful for you

**Comment by zychappy** [comment]
emm,the private must be in the wallet when using sign_memo,
it is wired that the key from sha512 is a [64]byte,but aes only accepts [32]byte
