### ISSUE TITLE
make generate error:stringer

### ISSUE THREAD

**Issue by qizikd** [denkhaus/bitshares#26]
When I execute make generate, I report an error

stringer: checking package: account_ffjson.go:7:2: could not import bytes (reading export data: /root/go/pkg/linux_amd64/bytes.a: invalid encoding format in export data: got 'i'; want 'c' or 'd')
types/types.go:3: running "stringer": exit status 1
Makefile:13: recipe for target 'generate' failed
make: [generate] Error 1 (ignored)

**Comment by denkhaus** [comment]
Hi, checkout dev branch, update dev dependencies with make init and your good to go. At least this works on my side.

**Comment by denkhaus** [comment]
If nobody complains I close this issue.
