### ISSUE TITLE
Operation type OperationTypeTransfer not yet supported

### ISSUE THREAD

**Issue by qizikd** [denkhaus/bitshares#27]
config.SetCurrentConfig(config.ChainIDBTS)
	rpcApiUrl    := ""
	wsFullApiUrl := "wss://bitshares.openledger.info/ws"

	api := api.New(wsFullApiUrl, rpcApiUrl)
	if err := api.Connect(); err != nil {
		log.Fatal(err)
	}

	api.OnError(func(err error) {
		log.Fatal(err)
	})

	user := types2.NewGrapheneID("1.2.1587421")
	start := types2.NewGrapheneID("1.11.0")
	stop := types2.NewGrapheneID("1.11.187658388")

	res, err := api.GetAccountHistory(user,stop,30,start)
	if err != nil {
		log.Fatal(err)
	}
	for _,v := range res {
		fmt.Println(v)
	}

**Comment by qizikd** [comment]
The output is as follows:

Operation type OperationTypeTransfer not yet supported
Operation type OperationTypeTransfer not yet supported
Operation type OperationTypeTransfer not yet supported
Operation type OperationTypeTransfer not yet supported
Operation type OperationTypeTransfer not yet supported
Operation type OperationTypeTransfer not yet supported
Operation type OperationTypeAccountCreate not yet supported
{1.11.830018841 36482411 37 0 21466 {OperationTypeTransfer <nil>} [0 map[]]}
{1.11.829877592 36479533 0 0 41597 {OperationTypeTransfer <nil>} [0 map[]]}
{1.11.829821676 36478306 61 0 36434 {OperationTypeTransfer <nil>} [0 map[]]}
{1.11.829819795 36478263 16 0 31889 {OperationTypeTransfer <nil>} [0 map[]]}
{1.11.829798488 36477835 15 0 36693 {OperationTypeTransfer <nil>} [0 map[]]}
{1.11.813051799 36103043 3 0 45513 {OperationTypeTransfer <nil>} [0 map[]]}
{1.11.785017255 35533789 2 0 60360 {OperationTypeAccountCreate <nil>} [1 1.2.1587421]}

**Comment by denkhaus** [comment]
I will look into it shortly

**Comment by denkhaus** [comment]
Hi look in branch dev commit ddf22d7.  I created a test in /tests/common_test.go for you which works flawelessly for me. 

```

//for qizikd
func (suite *commonTest) Test_GetAccountHistory_1() {

	user := types.NewAccountID("1.2.1587421")
	start := types.NewOperationHistoryID("1.11.0")
	stop := types.NewOperationHistoryID("1.11.187658388")

	res, err := suite.TestAPI.GetAccountHistory(user, stop, 30, start)
	if err != nil {
		suite.FailNow(err.Error(), "GetAccountHistory")
	}

	suite.NotNil(res)
	logging.Dump("history >", res)
}

```

**Comment by denkhaus** [comment]
If nobody complains I close this issue.
