### ISSUE TITLE
field type changed

### ISSUE THREAD

**Issue by Elbandi** [denkhaus/bitshares#28]
asset_options extenstion field changed the type. old was an array, new is a object:
https://github.com/bitshares/bitshares-core/blob/master/libraries/chain/include/graphene/chain/protocol/asset_ops.hpp#L85

sample return:
```
{
   "id":21,
   "jsonrpc":"2.0",
   "result":[
      {
         "id":"1.3.1570",
         "symbol":"BRIDGE.BTC",
         "precision":8,
         "issuer":"1.2.374566",
         "options":{
            "max_supply":"1000000000000000",
            "market_fee_percent":20,
            "max_market_fee":"100000000000",
            "issuer_permissions":69,
            "flags":5,
            "core_exchange_rate":{
               "base":{
                  "amount":100000,
                  "asset_id":"1.3.0"
               },
               "quote":{
                  "amount":4000,
                  "asset_id":"1.3.1570"
               }
            },
            "whitelist_authorities":[

            ],
            "blacklist_authorities":[

            ],
            "whitelist_markets":[

            ],
            "blacklist_markets":[
               "1.3.3756",
               "1.3.4474",
               "1.3.5050",
               "1.3.5092",
               "1.3.5112",
               "1.3.5145",
               "1.3.5146",
               "1.3.5171",
               "1.3.5182"
            ],
            "description":"{\"main\":\"Bitcoin\",\"market\":\"\"}",
            "extensions":{

            }
         },
         "dynamic_asset_data_id":"2.3.1570"
      }
   ]
}
```

this need to change: https://github.com/denkhaus/bitshares/blob/master/types/extensions.go

**Comment by denkhaus** [comment]
Hi @Elbandi this is a known issue addressed in dev branch. I will test and do a new release shortly.

**Comment by denkhaus** [comment]
@Elbandi , please look if we can close this issue for the newly pushed version 0.6.0

**Comment by Elbandi** [comment]
i try to port my code to 0.6.0, but i got some issue:
my golang 1.10.6, doesnt handle this lines: `invalid field name "Name" in struct initializer˙` https://github.com/denkhaus/bitshares/blob/master/config/chaincconfig.go#L62-L67

type issue (i query the account by name, and try to query the account history):

```
	account, err := api.GetAccountByName("evan")
	if err != nil {
		log.Fatalln(err)
	}
	start := types.NewOperationHistoryID("1.11.1000000")
	stop := types.NewOperationHistoryID("1.11.0")
	transactions, err := api.GetAccountHistory(account.ID, stop, 50, start)
```
error is: `cannot use account.ID (type types.AccountID) as type types.GrapheneObject in argument to api.GetAccountHistory:`

and same in processing transactions, try resolve the operation assets:
```
for _, transaction := range transactions {
	switch op := transaction.Operation.Operation.(type) {
	case *operations.FillOrderOperation:
	objects2, err := api.GetObjects(op.Pays.Asset, op.Receives.Asset, op.FillPrice.Base.Asset, op.FillPrice.Quote.Asset, op.Fee.Asset);
}
```
error: `cannot use op.Pays.Asset (type types.AssetID) as type types.GrapheneObject in argument to api.GetObjects:`
but i dont understand why not good , what do i wrong?

**Comment by denkhaus** [comment]
Please try again. Issue was fixed.

**Comment by Elbandi** [comment]
It works now.
